### ISSUE TITLE
quenstion about crf layer

### ISSUE THREAD

**Issue by ghost** [createmomo/CRF-Layer-on-the-Top-of-BiLSTM#3]
hi creatrmomo，I have some quentions about crf layer. first，in crf theory, the likelyhood function is based on the observations, as I see in this demo, the emission and transition score are only computed based on the lstm outputs, so should we name this layer crf?I think this name is not so accurate. Second, when we calculate all path scores, why use expression previous+obs+transitions, where previous is transposed? I am still confused . Thank you for your reply.

**Comment by createmomo** [comment]
Hi doggyChe, thanks for your feedback. As for the first one: in fact, in the CRF layer, only the emission score was from the LSTM outputs. The transition score matrix was a part of the CRF layer. The matrix would be trained during the training phase. In term of the name "CRF" layer, the theory of the CRF layer in the BiLSTM-CRF model is not the same as the original CRF, but the idea is similar to some degree. That might be the reason why some publications called the layer "CRF" layer.   Secondly, when computing the total score of all the paths, it is an efficient way to compute the total score by "previous+obs+transitions". "where previous is transposed?" Could you explain the meaning of "transposed" in your question? @doggyChe

**Comment by ghost** [comment]
for question 2, I read your blog again and made the dynamic algorithm clear. it is very beautiful, thanks for explaining this to me. But for question 1, I think the original CRF is based on the observation sequence, I mean there should be many emission matrice and transition matrices, or at least , the input words should be included in the emission and transition matrix, otherwise, the algorithm is just simply count the frequency of labels, because the last output is not observation sequence, but already the labels. Thank you for your reply.

**Comment by createmomo** [comment]
Yes, the "CRF" layer discussed in the posts was a bit different with the original CRF. But the general idea is similar. Probably you could propose a new and more robust CRF layer and publish a new paper. :)
