### ISSUE TITLE
How to save the trained model parameters？

### ISSUE THREAD

**Issue by ALein** [createmomo/CRF-Layer-on-the-Top-of-BiLSTM#5]
hello，If I want to save the parameters of the trained model for later use, what should I do？

**Comment by createmomo** [comment]
Hi there, may I know which framework are you using, PyTorch, Tensorflow or
Chainer?

**Comment by ALein** [comment]
PyTorch

**Comment by ALein** [comment]
I always use pytroch, but I see that your CRFLayer is written by chainer. I don't know much about this framework, so I want to know how to save the model

**Comment by createmomo** [comment]
Hi ALein, 

If you are using PyTorch, you may have been aware that it provides [a module for saving models](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

Similarly, chainer also has the [demo code](https://docs.chainer.org/en/stable/guides/serializers.html) for saving and loading models in its document.

Hope this would be helpful!
Best,
