### ISSUE TITLE
could you provide more details in this article?

### ISSUE THREAD

**Issue by ahmad-alismail** [createmomo/CRF-Layer-on-the-Top-of-BiLSTM#6]
Hello, Thank you for explaining CRF layer. Could you provide more information in this article so I could reference it in my thesis?
Thank you in advance!

**Comment by createmomo** [comment]
Hi, thank you very much for your positive comment! 

If you want to cite the article, you can directly cite the link to the article, for example:
https://createmomo.github.io/2017/09/12/CRF_Layer_on_the_Top_of_BiLSTM_1/

Alternatively, if you want to cite the work/model/architecture/idea of CRF layer on the top of BiLSTM, I suggest that you can cite the original paper:
https://www.aclweb.org/anthology/N16-1030/

Hope this comment helps!

:)

**Comment by ahmad-alismail** [comment]
Thank you for reply,
I want to cite your article, but I need at least the name of the author and publish date... You have explained more than lample (2016). Therefore, I hope if you could provide me a name please :)

**Comment by createmomo** [comment]
> Thank you for reply,
> I want to cite your article, but I need at least the name of the author and publish date... You have explained more than lample (2016). Therefore, I hope if you could provide me a name please :)

Thank you for your kind response. May I have your email, thus I can share my name? :)

**Comment by ahmad-alismail** [comment]
Thank you very much!
Ahmad.Alismail@stud.uni-regensburg.de
